name: Test & Publish

on:
  push:
    branches: [ main ]
    tags:   [ "v*" ]
  pull_request:
    branches: [ main ]

jobs:
  ###########################################################################
  # Test matrix (build PyGObject for the active interpreter in each job)
  ###########################################################################
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install system libraries (headers + GStreamer introspection)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgirepository-2.0-dev gobject-introspection libcairo2-dev libffi-dev pkg-config gcc libglib2.0-dev \
            gstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools \
            gir1.2-gstreamer-1.0 \
            gir1.2-gst-plugins-base-1.0

      - name: Build PyGObject and project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycairo PyGObject
          if [ -f requirements.txt ];      then pip install -r requirements.txt      ; fi
          pip install -e .[dev]

      - name: Check dependencies
        run: |
          python check_dependencies.py

      - name: Run tests
        run: |
          USE_REAL_CAMERA=false pytest tests/ -v --maxfail=1 -rs

  ###########################################################################
  # Build and publish to PyPI on version tags
  ###########################################################################
  build-and-publish:
    needs: test
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-3.11-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-3.11-pip-

      - name: Install system libraries (headers + GStreamer introspection)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgirepository-2.0-dev gobject-introspection libcairo2-dev libffi-dev pkg-config gcc libglib2.0-dev \
            gstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-tools \
            gir1.2-gstreamer-1.0 \
            gir1.2-gst-plugins-base-1.0

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycairo PyGObject
          pip install build twine

      - name: Build and verify wheel & sdist
        run: |
          python -m build
          twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
